### ISSUE TITLE
로그

### ISSUE THREAD

**Issue by Bixbyi** [MisileLab/FurLuck-Bot#3]
봇이 수정해도 수정 로그가 떠요
![image](https://user-images.githubusercontent.com/66349321/119355423-37374f80-bce0-11eb-96e3-18f412b1a558.png)![image](https://user-images.githubusercontent.com/66349321/119355470-46b69880-bce0-11eb-9ac7-8f1a91c83095.png)

이미지가 로딩 된 후 사진이 뜰 때 수정 로그가 떠요 
![image](https://user-images.githubusercontent.com/66349321/119355339-1b33ae00-bce0-11eb-83c8-f9ec59b71fb4.png)
(.webm은 이미지 파일입니다.)

**Comment by MisileLab** [comment]
수정 완료
