### ISSUE TITLE
Log message's some bugs

### ISSUE THREAD

**Issue by kyjkyj080115** [MisileLab/FurLuck-Bot#4]
# First. When users send image, The bot send same link
![image](https://user-images.githubusercontent.com/71873121/119356013-e4aa6300-bce0-11eb-8a95-367eb1a7ac5c.png)

# Second. It even sends a log when a bot's message is edited or deleted.
![image](https://user-images.githubusercontent.com/71873121/119356249-2e934900-bce1-11eb-91ec-e76c2faaa7d1.png)
![image](https://user-images.githubusercontent.com/71873121/119356300-3c48ce80-bce1-11eb-9906-3886f57cfade.png)

# Last. Users send links, bot send logs
![image](https://user-images.githubusercontent.com/71873121/119356664-a6fa0a00-bce1-11eb-9e22-fffdf6622e39.png)

# Many users feel damage and discomfort to this.

**Comment by MisileLab** [comment]
Fixed
